name: CD
on:
  push:
    tags:
      - '*'
concurrency:
  group: production
  cancel-in-progress: true
env:
  RUST_VERSION_STABLE: 1.82.0
  CRATE_PATHS: .
jobs:
  released:
    runs-on: ubuntu-latest
    needs: lint-rust
    environment: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true
      - name: Building
        run: cargo build --release --all-targets
      - name: Publishing
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo publish -vv --all-features
